name: 阿里云函数部署
on:
  # schedule:
  #   - cron: '10 1,8,15 * * *'
  workflow_dispatch:
  push:
    # paths:
    #   - 'src/*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ALI_KEYID: ${{ secrets.ALI_KEYID }}
      ALI_KEYSECRET: ${{ secrets.ALI_KEYSECRET }}
      ALI_ACCOUNTID: ${{ secrets.ALI_ACCOUNTID }}
      PT_PIN: ${{ secrets.PT_PIN }}
      PT_KEY: ${{ secrets.PT_KEY }}
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
      ALL_SECRETS: ${{ toJson(secrets) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: set serverless.yml and push env
        run: |
          npm install @serverless-devs/s -g
          s config add --AccessKeyID $ALI_KEYID --AccessKeySecret $ALI_KEYSECRET --AccountID $ALI_ACCOUNTID
          mkdir -p ./start-fc-event-nodejs14/code/config
          cp -r ./*.js ./start-fc-event-nodejs14/code
          cp -r ./src/config/*.* ./start-fc-event-nodejs14/code/config
          cd ./start-fc-event-nodejs14
          s deploy -y --use-local
